name: Main CI # action 명

on: # 이벤트 트리거
  push: # push event에 반응
    branches: # github repository의 branch가 
      - master # master 일 경우만

jobs: # jobs
  build: # GitHub-hosted runners env
    runs-on: ubuntu-18.04 # using Ubuntu 18.04 LTS
    steps: # steps
      - name: git clone # 
        uses: actions/checkout@v2 # 

      - name: npm install # 
        run: npm install # npm install

      - name: build # 
        run: npm run build # code build

      - name: deploy # 배포 내 app과 이름이 같아야 함
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://pcs-ver.2
